### ISSUE TITLE
VEM voicepack Is to low

### ISSUE THREAD

**Issue by eclisauce** [DeadlyBossMods/DBM-Voicepack-VEM#1]
Is there any way of making the voice get louder so I can hear it?

**Comment by henryj** [comment]
In your game system sound setting, turn up the master voice and down other
sub voice options.

**Comment by eclisauce** [comment]
now I feel really stupid but I can't find the Master voice

**Comment by henryj** [comment]
Sorry. It might not be the exact word. I don't have the game at the moment.
Should be in system->sound-> main volume or something. And there're other
sub volumes under that. Just turn others down and keep the main one up.

**Comment by MysticalOS** [comment]
Also, if special warning sounds covering voice. You can enable option to disable special warning sounds for warnings that have spoken alerts (forget exact way i worded option)
