### ISSUE TITLE
Only target's casts announced

### ISSUE THREAD

**Issue by nicknobis** [DeadlyBossMods/DBM-Voicepack-VEM#10]
Hi, I've been having an issue with DBM, specifically in mythic plus, where only the target's casts were announced through VEM.

I'm not sure if this is an issue with DBM or VEM, but if there's a solution, I haven't been able to find it. Thank you for any insight you can provide :)

**Comment by MysticalOS** [comment]
That's much too vague of a report. targets cast of what? what dungeon what boss what spell.
