### ISSUE TITLE
DBM Voice Alerts not working 

### ISSUE THREAD

**Issue by darenjacobs** [DeadlyBossMods/DBM-Voicepack-VEM#15]
**As of Shadowlands Season 4 launch Tuesday, August 2, 2022 DBM VoicePack is not working and I removed it, as it is deprecated but it still doesn't work**

I am expecting Voice alerts which I no longer receive while playing

When I do /dbm - Options - Spoken Alerts, the area "Set voice for spoken Alerts used to have "VEM English Female", Now it says 
"Missing Voice Pack {VEM}".  

Please note I have removed the addon dbm-voicepack-vem - https://www.curseforge.com/wow/addons/dbm-voicepack-vem

How can I get spoken alerts back? 
![dbm voice not working](https://user-images.githubusercontent.com/4740431/183087244-69e04a15-e47e-4106-8bca-dac9493d2f27.PNG)

**Comment by darenjacobs** [comment]
Also, Right before it stopped working, the spoke alerts were missing warnings in Tazavesh: So'leah's Gambit for fishsticks cast and dragon breath.  It used to say "interrupt" for the cast and "run" for the breath.

**Comment by QartemisT** [comment]
Are you ssure that DBM VoicePack is enabled in your addons list? It looks like it's either misssing or disabled :)
