### ISSUE TITLE
Voice change/quality on kick5r.ogg & new thogar sounds

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Voicepack-VEM#3]
It seems you are using a new TTS voice for kick5r.ogg and some of the new thogar sounds. The quality of new recordings are much lower plus the voice doesn't match rest of pack. The old voice/TTS sounds much better. Can these files be recorded in that voice?

**Comment by henryj** [comment]
Yeah. That's temporary. I'm not able to access the original voice lib for
the moment. Will regenerate later this week.

**Comment by MysticalOS** [comment]
Excellent. I figured something along those lines. Keep up amazing work.
Don't mind me asking, what tools do you use to generate anyways?

**Comment by henryj** [comment]
I've got a friend who used to generate those for me. I believe he's using Balabolka and has Ivona 2 TTS voice Amy-UK installed on his computer. As he's too busy and quitting WoW these days I guess I'll find a way to automate this process with http://www.ivona.com/ cloud service or install those tools on my pc... 

BTW,  the Demo ones are generated by voicerss.org api which has been automated already... but as you realised it's not the same quality as the ivona ones.
