### ISSUE TITLE
Curse client suckage

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Voicepack-VEM#5]
It seems curse client sucks at detecting when this is updated for some reason. It often thinks user is up to date even if they are 2 versions behind or whatever. It doesn't have this issue with russian pack, As far as I can tell the only thing he's actually doing differently, is updating ToC every time with his own version number

So while this isn't a requirement by DBM, to maximize your user downloads, I recommend something like
"## Version: 1.3"
or whatever in toc file just to make curse client be less fail and distribute your updates properly on curse and not improperly inform users they are up to date when in fact they are not. Then just bump that arbitrary version every update.

I THINK this will solve issues with curse client but maybe i overlooked something else VPAlyona is doing, but I don't think so.

**Comment by MysticalOS** [comment]
Looks like you have a version field, just don't update it every release. So just making sure to increment it in updates should solve it.

**Comment by henryj** [comment]
Thanks. That's very helpful. 9367a37000b8ad49d4f2e97f17fadefbed9fb457

**Comment by MysticalOS** [comment]
Yep, that seems to fix it. Curse client is seeing update better now.

**Comment by henryj** [comment]
Perfect.
