### ISSUE TITLE
New Thogar sounds needed for mythic

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Voicepack-VEM#6]
A23, D1C4, E1A23, B2A4, E23

Key
--  A: just rushing through the lane(express)
--  B: small Adds(Reinforcements)
--  C: cannon
--  D: big Adds (ManOArms)
--  E: fire(Deforester) 
--  F: random express (3x trainType A)
--  X: random rail

**Comment by henryj** [comment]
ok. on it. btw, any version no. increase?

**Comment by MysticalOS** [comment]
For the train stuff, nah. In this specific case, the train sounds don't actually replace any special warning alerts, so no filter updates.
