### ISSUE TITLE
It calls wrong marks for the latest version of DBM on Wrath of Gul'dan marks when the setting based on role is used.

### ISSUE THREAD

**Issue by epigramx** [DeadlyBossMods/DBM-Voicepack-VEM#7]
On the latest stable version of DBM on both leader and member, this addon calls a wrong mark for Wrath of Gul'dan ("go to [mark]") when the setting to use marks based on role in DBM is used. That is a recent change of DBM.

**Comment by Mini-Dragon** [comment]
Can you give us more info in detail?

**Comment by epigramx** [comment]
More info

http://forums.elitistjerks.com/forums/topic/134171-request-wrath-of-guldan-icons-depending-on-member-role/?page=2#comment-2285246

(answer to the previous post there)
