### ISSUE TITLE
missing sounds - DBM v8.0.1-2-ge2a6f2cbf-alpha

### ISSUE THREAD

**Issue by R-Adrian** [DeadlyBossMods/DBM-Voicepack-VEM#8]
i updated to DBM v8.0.1-2-ge2a6f2cbf-alpha and now i'm getting this message:
![wowscrnshot_072318_132525](https://user-images.githubusercontent.com/16319504/43071716-537d0102-8e7c-11e8-8b76-771b84db2849.jpg)

( note: using DBM-VPVEM-6ad2971 from CurseForge )

**Comment by henryj** [comment]
Thanks for the feedback. We are still waiting for DBM team to send us the new voices' list. We'll update once we've got them.

**Comment by henryj** [comment]
version number updated
