### ISSUE TITLE
DBM VEM shows as an out of date addon

### ISSUE THREAD

**Issue by Sinaloit** [DeadlyBossMods/DBM-Voicepack-VEM#9]
Voicepack shows as out of date still.

https://github.com/henryj/DBM-Voicepack-VEM/blob/082471abf9ef3b86de337abb39f34fb6ed14013c/DBM-VPVEM/DBM-VPVEM.toc#L1-L2

DBM Shows the above lines to both be: 80000

**Comment by henryj** [comment]
version number updated
